# Generated by Django 3.1.3 on 2020-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='blue', max_length=15, verbose_name='Цвет'),
        ),
    ]
